### ISSUE TITLE
The pattern_to_regex method does not seem to work correctly on windows.

### ISSUE THREAD

**Issue by hakancelikdev** [cpburnz/python-pathspec#63]
gitignore file is as follows.

```
a
b
spam/**
**/api/
**/
```

After converting each line to regex, I have a method called list_path that scans the python files in the current directory and returns the ones that do not match each pattern found in gitignore, and the following test failed in the Windows environment, do you have Windows support for Pathspec?

- https://github.com/hakancelikdev/unimport/blob/i240/tests/test_utils.py#L34
- https://github.com/hakancelikdev/unimport/runs/8173619404?check_suite_focus=true

**Comment by excitoon** [comment]
@hakancelikdev It does not support `**/`. `gitignorefile` shall do the job.

**Comment by excitoon** [comment]
Nope, it was probably fixed in #62 .

**Comment by hakancelikdev** [comment]
Okey thank you

**Comment by cpburnz** [comment]
@hakancelikdev Windows is supported by normalizing the Windows path to a POSIX path, and then matching it against the compiled regular expression patterns. If you're using the `PathSpec` or `GitIgnoreSpec` classes, they'll handle the normalization for you. Otherwise, you'll need to normalize them with the `pathspec.util.normalize_file()` function before matching them with the patterns.

For the test that's failing, I'm not sure how `utils.test_paths()` or `utils.get_exclude_list_from_gitignore()` use *pathspec* as those appear to be from *unimport*.
